listapelis=[
    {
        "Titulo":"La Laguna Azul",
        "Generos":["Romance", "Drama"],
        "Año": "1980",
        "Reparto":"Brooke Shields, Christopher Atkins",
        "Disponibilidad":5,
        "Rating":3.5,
    },
    {
        "Titulo":"Her",
        "Generos":["Romance","Ciencia Ficción"],
        "Año":"2013",
        "Reparto":"Joaquin Phoenix",
        "Disponibilidad":3,
        "Rating":4,
    },
    {
        "Titulo":"Drive",
        "Generos":["Acción"],
        "Año":"2011",
        "Reparto":"Ryan Gosling",
        "Disponibilidad":1,
        "Rating":3,
    },
    {
        "Titulo":"Whiplash",
        "Generos":["Suspenso", "Drama"],
        "Año":"2014",
        "Reparto":"Miles Teller, J.K Simmons",
        "Disponibilidad":7,
        "Rating":5,
    },
    {
        "Titulo":"Historia de un Matrimonio",
        "Generos":["Romance","Drama"],
        "Año":"2014",
        "Reparto":"Adam Driver, Scarlett Johanson",
        "Disponibilidad":4,
        "Rating":3,
    },
    {
        "Titulo":"Mente indomable",
        "Generos":["Romance","Drama"],
        "Año":"1997",
        "Reparto":"Matt Damon, Ben Affleck",
        "Disponibilidad":2,
        "Rating":2,
    },
    {
        "Titulo":"Como Entrenar a tu Dragón",
        "Generos":["Animación","Aventura"],
        "Año":"2010",
        "Reparto":"",
        "Disponibilidad":5,
        "Rating":5,
    },
    {
        "Titulo":"El viaje de Chihiro",
        "Generos":["Animación"],
        "Año":"2001",
        "Reparto":"",
        "Disponibilidad":8,
        "Rating":5,
    },
    {
        "Titulo":"La Langosta",
        "Generos":["Drama"],
        "Año":"2015",
        "Reparto":"Collin Farrell",
        "Disponibilidad":1,
        "Rating":3,
    },
    {
        "Titulo":"The Basketball Diaries",
        "Generos":["Drama"],
        "Año":"2015",
        "Reparto":"Leonardo Di Caprio",
        "Disponibilidad":6,
        "Rating":3.5,
    },
    {
        "Titulo":"Titanic",
        "Generos":["Drama"],
        "Año":"1991",
        "Reparto":"Leonardo Di Caprio",
        "Disponibilidad":0,
        "Rating":4.5,
    },
    {
        "Titulo":"The Talented Mr Ripley",
        "Generos":["Drama"],
        "Año":"1999",
        "Reparto":"Jude Law, Matt Damon",
        "Disponibilidad":3,
        "Rating":3,
    },
    {
        "Titulo":"Ghost Rider",
        "Generos":["Aventura"],
        "Año":"2007",
        "Reparto":"Nicolas Cage",
        "Disponibilidad":5,
        "Rating":4,
    }
]